title: MobilePay Subscriptions
base_url: https://mobilepaydev.github.io/MobilePay-Subscriptions/
description: MobilePay Subscriptions API documentation.
show_downloads: false
theme: jekyll-theme-minimal
repository: MobilePayDev/MobilePay-Subscriptions
google_analytics: UA-92933803-2