title: MobilePay Subscriptions
base_url: http://localhost:4000/
description: MobilePay Subscriptions API documentation.
show_downloads: false
theme: jekyll-theme-minimal
repository: MobilePayDev/MobilePay-Subscriptions
google_analytics: UA-92933803-2