title: MobilePay Subscriptions
description: MobilePay Subscriptions description
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
repository: DanskeBank/MobilePay-Subscriptions
google_analytics: UA-92933803-1